/**
 * WolfHome Hungarian Nameday Database
 */
export const namedayDB = {
    1: ["Újév", "Ábel", "Genovéva", "Titusz", "Simon", "Boldizsár", "Attila", "Ramóna", "Marcell", "Melánia", "Ágota", "Ernő", "Veronika", "Bódog", "Lóránt", "Gusztáv", "Antal", "Piroska", "Sára", "Fábián", "Ágnes", "Vince", "Zelma", "Timót", "Pál", "Vanda", "Angyalka", "Károly", "Adél", "Martina", "Gerda"],
    2: ["Ignác", "Karolina", "Balázs", "Ráhel", "Ágota", "Dorottya", "Tódor", "Aranka", "Abigél", "Elvira", "Bertold", "Lívia", "Ella", "Bálint", "Kolos", "Julianna", "Donát", "Bernadett", "Zsuzsanna", "Aladár", "Eleonóra", "Gerzson", "Alfréd", "Mátyás", "Géza", "Edina", "Edvin", "Elemér", "Oszkár"],
    3: ["Albin", "Lujza", "Kornélia", "Kázmér", "Adorján", "Leonóra", "Tamás", "Zoltán", "Franciska", "Ildikó", "Szilárd", "Gergely", "Krisztián", "Matild", "Kristóf", "Henrietta", "Gertrúd", "Sándor", "József", "Klaudia", "Benedek", "Beáta", "Emőke", "Gábor", "Irén", "Emánuel", "Hajnalka", "Gedeon", "Auguszta", "Zalán", "Árpád"],
    4: ["Hugó", "Áron", "Richárd", "Izidor", "Vince", "Vilmos", "Herman", "Dénes", "Erhard", "Zsolt", "Leó", "Gyula", "Ida", "Tibor", "Anasztázia", "Csongor", "Rudolf", "Andrea", "Emma", "Tivadar", "Konrád", "Csilla", "Béla", "György", "Márk", "Ervin", "Zita", "Valéria", "Péter", "Katalin"],
    5: ["Fülöp", "Zsigmond", "Tímea", "Mónika", "Györgyi", "Ivett", "Gizella", "Mihály", "Gergely", "Ármin", "Ferenc", "Pongrác", "Szervác", "Bonifác", "Zsófia", "Mózes", "Paszkál", "Erik", "Ivó", "Bernát", "Konstantin", "Júlia", "Dezső", "Eszter", "Orbán", "Fülöp", "Hella", "Emil", "Magdolna", "Zsanett", "Angéla"],
    6: ["Tünde", "Kármen", "Kornél", "Bulcsú", "Fatime", "Norbert", "Róbert", "Medárd", "Félix", "Margit", "Barnabás", "Villő", "Antal", "Vazul", "Jolán", "Jusztin", "Laura", "Arnold", "Gyárfás", "Rafael", "Alajos", "Paulina", "Zoltán", "Iván", "Vilmos", "János", "László", "Levente", "Péter", "Pál"],
    7: ["Tihamér", "Ottó", "Kornél", "Ulrik", "Emese", "Antal", "Apollónia", "Ellák", "Lukrécia", "Amália", "Nóra", "Izabella", "Jenő", "Örs", "Henrik", "Valter", "Endre", "Frigyes", "Emília", "Illés", "Dániel", "Magdolna", "Lenke", "Kinga", "Kristóf", "Anna", "Olga", "Szabolcs", "Márta", "Judit", "Oszkár"],
    8: ["Boglárka", "Lehel", "Hermina", "Dominika", "Krisztina", "Berta", "Ibolya", "László", "Emőd", "Lőrinc", "Zsuzsanna", "Klára", "Ipoly", "Marcell", "Mária", "Ábrahám", "Jácint", "Ilona", "Huba", "István", "Sámuel", "Menyhért", "Bence", "Bertalan", "Lajos", "Izsó", "Gáspár", "Ágoston", "Beatrix", "Rózsa", "Erika"],
    9: ["Egyed", "Rebeka", "Hilda", "Rozália", "Viktor", "Zakariás", "Regina", "Mária", "Ádám", "Nikolett", "Teodóra", "Mária", "Kornél", "Szeréna", "Enikő", "Edit", "Zsófia", "Diána", "Vilhelmina", "Friderika", "Máté", "Móric", "Tekla", "Gellért", "Eufrozina", "Justina", "Adalbert", "Vencel", "Mihály", "Jeromos"],
    10: ["Malvin", "Petra", "Helga", "Ferenc", "Aurél", "Brúnó", "Amália", "Koppány", "Dénes", "Gedeon", "Brigitta", "Miksa", "Kálmán", "Helén", "Teréz", "Gál", "Hedvig", "Lukács", "Vendel", "Vendel", "Orsolya", "Előd", "Gyöngyi", "Salamon", "Blanka", "Dömötör", "Szabina", "Simon", "Nárcisz", "Alfonz", "Farkas"],
    11: ["Marianna", "Achilles", "Győző", "Károly", "Imre", "Lénárd", "Rezső", "Zsombor", "Tivadar", "Réka", "Márton", "Jónás", "Szilvia", "Aliz", "Albert", "Ödön", "Hortenzia", "Jenő", "Erzsébet", "Jolán", "Olivér", "Cecília", "Kelemen", "Emma", "Katalin", "Virág", "Virgil", "Stefánia", "Taksony", "András"],
    12: ["Elza", "Melinda", "Ferenc", "Borbála", "Vilma", "Miklós", "Ambrus", "Mária", "Natália", "Judit", "Árpád", "Gabriella", "Luca", "Szilárda", "Valér", "Etelka", "Lázár", "Auguszta", "Viola", "Teofil", "Tamás", "Zénó", "Viktória", "Ádám", "Karácsony", "István", "János", "Kamilla", "Tamás", "Dávid", "Szilveszter"]
};
